jobs:
  rdp-access:
    runs-on: windows-2022
    steps:
      - name: Enable RDP
        run: |
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          net user github Password@123 /add
          net localgroup "Remote Desktop Users" github /add
          Write-Host "RDP Enabled Successfully!"
        shell: powershell

      - name: Download LocalXpose
        run: |
          Invoke-WebRequest -Uri "https://loclx-client.s3.amazonaws.com/loclx-windows-amd64.zip" -OutFile "localxpose.zip"
          Expand-Archive -Path "localxpose.zip" -DestinationPath "./localxpose"
        shell: powershell

      - name: Authenticate LocalXpose
        run: ./localxpose/loclx.exe authtoken "LOCX_AUTH_TOKEN"
        shell: powershell

      - name: Expose RDP Port
        run: ./localxpose/loclx.exe tcp --to 3389
        shell: powershell
