name: LocalXpose Tunnel  

on:  
  push:  
    branches: [main]  

jobs:  
  expose-service:  
    runs-on: windows-latest  

    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v3  

      - name: Download and Extract LocalXpose  
        run: |  
          Invoke-WebRequest -Uri "https://loclx-client.s3.amazonaws.com/loclx-windows-amd64.zip" -OutFile "localxpose.zip"  
          Expand-Archive -Path "localxpose.zip" -DestinationPath "./localxpose"  

      - name: Authenticate LocalXpose  
        run: ./localxpose/loclx.exe authtoken "YOUR_LOCALXPOSE_AUTH_TOKEN"  

      - name: Start LocalXpose Tunnel  
        run: ./localxpose/loclx.exe tunnel http --to 127.0.0.1:54537  
