name: RDP Access

on: [push, workflow_dispatch]

jobs:
  rdp-access:
    runs-on: windows-latest

    steps:
    - name: Download LocalXpose (`loclx`)
      run: Invoke-WebRequest https://api.localxpose.io/api/v2/downloads/loclx-windows-amd64.zip -OutFile loclx.zip

    - name: Extract LocalXpose
      run: Expand-Archive loclx.zip

    - name: Authenticate LocalXpose
      run: .\loclx\loclx.exe account login $Env:LOCX_AUTH_TOKEN
      env:
        LOCXPOSE_AUTH_TOKEN: ${{ secrets.LOCXPOSE_AUTH_TOKEN }}

    - name: Enable RDP & Firewall Rules
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Create a New User
      run: |
        net user github Password@123 /add
        net localgroup "Remote Desktop Users" github /add

    - name: Start LocalXpose TCP Tunnel
      run: .\loclx\loclx.exe tunnel tcp --port 3389
